services:
  converter-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ./:/workspace
      - ./data:/data
    working_dir: /workspace
    restart: unless-stopped